spring:
  application:
    name: item-service
    rabbitmq:
      host: 192.168.64.140
      port: 5672
      username: admin
      password: admin
#server:
#  port: 8001
eureka:
  client:
    service-url:
      #结合云服务器才能设置其它选项
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
      
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
  